### ISSUE TITLE
ERROR in ./src/app.ts

### ISSUE THREAD

**Issue by TheoMer** [sararob/angular2base#7]
OS: Windows 10 Pro
NPM ver: 3.5.3

Hi,

So, the following error message is being generated when processing the following command, 'npm run build':

'ERROR in ./src/app.ts
Module build failed: TypeError: compiler.parseConfigFile is not a function
    at ensureTypeScriptInstance (C:\Users\Theo\Documents\Projects\angular2base-master\node_modules\ts-loader\index.js:147:38)
    at Object.loader (C:\Users\Theo\Documents\Projects\angular2base-master\node_modules\ts-loader\index.js:365:14)'

What is the issue here?

**Comment by JoshWilliams92** [comment]
I have the same issue, let me know if you manage to fix it or not.

**Comment by anned20** [comment]
I don't know if you fixed it yet but:
Change this in package.json:
`"typescript": "^1.6.2"`
to `"typescript": "~1.6.2"`

It's because Angular only works with TS 1.6.2 at the moment

**Comment by JoshWilliams92** [comment]
Yes this worked, thanks so much!

**Comment by anned20** [comment]
No problem man! Glad it works
